Finanzas/urls.py
from django.contrib import admin
from django.urls import path, include
from gestion import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestion/',include('gestion.urls')),
    path('accounts/', include('django.contrib.auth.urls') ),
    path('',views.index)
]

gestion/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name='gestion'
urlpatterns=[
    path('',views.index,name='index'),
    path('crear/empleado',views.index,name='index2'),

    path('crear/balance',views.crearBalance,name='crearBalance'),
    path('detalle/balance/<int:pk>',views.detalleBalance,name='detalleBalance'),
    path('actualizar/balance/<int:pk>',views.actualizarBalance,name='actualizarBalance'),
    path('eliminar/balance/<int:pk>',views.eliminarBalance,name='eliminarBalance'),
    
    path('crear/estadoresultados',views.crearEstadoResultados,name='crearEstadoResultados'),
    path('detalle/estadoresultados/<int:pk>',views.detalleEstadoResultados,name='detalleEstadoResultados'),
    path('actualizar/estadoresultados/<int:pk>',views.actualizarEstadoResultados,name='actualizarEstadoResultados'),
    path('eliminar/estadoresultados/<int:pk>',views.eliminarEstadoResultados,name='eliminarEstadoResultados'),

    path('factibilidad/',views.factibilidad,name="factibilidad"),
    path('detalle/empleado/<int:pk>',views.detalleEmpleado,name="detalleEmpleado"),
    path('actualizar/empleado/<int:pk>',views.actualizarEmpleado,name="actualizarEmpleado"),
    path('eliminar/empleado/<int:pk>',views.eliminarEmpleado,name="eliminarEmpleado")
]

gestion/models.py
from django.db import models
from django.conf import settings
from datetime import date, datetime
# Create your models here.

# modelo para el balace general
class BalanceGeneral(models.Model):
    #activo circulante
    disponible = models.FloatField(default=0)
    valoresNegociables = models.FloatField(default=0)
    deudoresPorVenta = models.FloatField(default=0)
    deudoresVarios = models.FloatField(default=0)
    impuestosPorRecuperar = models.FloatField(default=0)


    #pasivo circulante
    cuentaPorPagar = models.FloatField(default=0)
    provedores = models.FloatField(default=0)
    retenciones = models.FloatField(default=0)
    convenioConInstituciones = models.FloatField(default=0)
    otros = models.FloatField(default=0)

    #activo fijo
    mueblesUtiles = models.FloatField(default=0)
    maquinariaEquipoOficina = models.FloatField(default=0)
    otrosActivosFijos = models.FloatField(default=0)
    equipoTransporte = models.FloatField(default=0)

    #pasivo fijo
    acredoresHipotecarios = models.FloatField(default=0)

    #otros activos
    programasComputacionales = models.FloatField(default=0)
    otros2 = models.FloatField(default=0)
    amortizaciones = models.FloatField(default=0)

    #capital contable
    capitalSocial = models.FloatField(default=0)
    utilidadesRetenidas = models.FloatField(default=0)

    fechaCreacion = models.DateField(default=datetime.now)
    creador = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

    def __str__(self):
        return '{} {}'.format(self.creador,self.fechaCreacion)

# modelo para el estado de resultados
class EstadoResultados(models.Model):
    #activo circulante 28 campos en total
    ventas = models.FloatField(default=0)
    devolucionesVentas = models.FloatField(default=0)
    descuentosVentas = models.FloatField(default=0)
    bonifRebVentas = models.FloatField(default=0)

    inventarioInicial = models.FloatField(default=0)
    compras = models.FloatField(default=0)
    fletesCompras = models.FloatField(default=0)
    gastosImportacion = models.FloatField(default=0)

    devolucionesCompras = models.FloatField(default=0)
    descuentosCompras = models.FloatField(default=0)
    bonificacionCompras = models.FloatField(default=0)

    inventarioFinal = models.FloatField(default=0)

    sueldoVendedores = models.FloatField(default=0)
    comisionVenta = models.FloatField(default=0)
    propaganda = models.FloatField(default=0)
    impuestosMunicipales = models.FloatField(default=0)

    gastosAlquiler = models.FloatField(default=0)
    gastosGenerales = models.FloatField(default=0)
    sueldoAdministracion = models.FloatField(default=0)
    perdidasCuentasMalas = models.FloatField(default=0)

    alquileresGanados = models.FloatField(default=0)
    interesesGanados = models.FloatField(default=0)
    comisionesGanadas = models.FloatField(default=0)

    interesesGastos = models.FloatField(default=0)
    perdidasVentas = models.FloatField(default=0)
    perdidaEnRoboMercancia = models.FloatField(default=0)

    fechaCreacion = models.DateField(default=datetime.now)
    creador = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

    def __str__(self):
        return '{} {}'.format(self.creador,self.fechaCreacion)


# modelo para el tipo de empleado
class TipoEmpleado(models.Model):
    #activo circulante 28 campos en total
    nombre = models.CharField(max_length=50)
    salario = models.FloatField(default=0)
    descripcion = models.CharField(max_length=60)
    def __str__(self):
        return '{}'.format(self.nombre)

# modelo para el tipo de empleado
class Empleado(models.Model):
    #activo circulante 28 campos en total
    nombre = models.CharField(max_length=50)
    ap_paterno = models.CharField(max_length=40)
    ap_materno = models.CharField(max_length=40)
    email = models.CharField(max_length=50)
    telefono = models.CharField(max_length=10)
    fechaCreacion = models.DateField(default=datetime.now)
    creador = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    # para las horas que va a trabajar
    horas = models.IntegerField()
    puesto = models.ForeignKey(TipoEmpleado,on_delete=models.CASCADE)
    def __str__(self):
        return '{}'.format(self.nombre)

gestion/forms.py
from django import forms
from .models import BalanceGeneral

gestion/views.py
from datetime import datetime
from django.db import reset_queries
from django.http import HttpResponse, Http404
from django.shortcuts import render
from .models import BalanceGeneral, EstadoResultados, TipoEmpleado, Empleado
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
# Create your views here.


#pagina de inicio
def index(request):
    #guardamos la lista de balance general del usuario en especifico
    balance=''
    estadoResultados=''
    if str(request.user) != 'AnonymousUser':
        balance = BalanceGeneral.objects.filter(creador=request.user)
        estadoResultados=EstadoResultados.objects.filter(creador=request.user)
    contexto={
        'listaBalance':balance,
        'listaEstadoResultados':estadoResultados
    }
    return render(request,'gestion/index.html',contexto)

#----------------------------------------------------- Balance -------------------------------------

# crear balance
@login_required
def crearBalance(request):
    
    if request.method == 'GET':
        contexto = {
            
        }
        return render(request,'gestion/balance.html',contexto)

    elif request.method == 'POST':
        disponible= request.POST['disponible']
        valoresNegociables = request.POST['valoresNegociables']
        deudoresPorVenta = request.POST['deudoresPorVenta']
        deudoresVarios = request.POST['deudoresVarios']
        impuestosPorRecuperar = request.POST['impuestosPorRecuperar']


        #pasivo circulante
        cuentaPorPagar = request.POST['cuentaPorPagar']
        provedores = request.POST['provedores']
        retenciones = request.POST['retenciones']
        convenioConInstituciones = request.POST['convenioConInstituciones']
        otros = request.POST['otros']

        #activo fijo
        mueblesUtiles = request.POST['mueblesUtiles']
        maquinariaEquipoOficina = request.POST['maquinariaEquipoOficina']
        otrosActivosFijos = request.POST['otrosActivosFijos']
        equipoTransporte = request.POST['equipoTransporte']

        #pasivo fijo
        acredoresHipotecarios = request.POST['acredoresHipotecarios']

        #otros activos
        programasComputacionales = request.POST['programasComputacionales']
        otros2 = request.POST['otros2']
        amortizaciones = request.POST['amortizaciones']

        #capital contable
        capitalSocial = request.POST['capitalSocial']
        utilidadesRetenidas = request.POST['utilidadesRetenidas']

        fechaCreacion = request.POST['fechaCreacion']

        balance = BalanceGeneral()
        balance.pk

        balance.disponible = disponible if disponible != '' else 0
        balance.valoresNegociables = valoresNegociables if valoresNegociables != '' else 0
        balance.deudoresPorVenta = deudoresPorVenta if deudoresPorVenta != '' else 0
        balance.deudoresVarios = deudoresVarios  if deudoresVarios != '' else 0
        balance.impuestosPorRecuperar = impuestosPorRecuperar if impuestosPorRecuperar != '' else 0

        balance.mueblesUtiles = mueblesUtiles if mueblesUtiles != '' else 0
        balance.maquinariaEquipoOficina = maquinariaEquipoOficina if maquinariaEquipoOficina != '' else 0
        balance.otrosActivosFijos = otrosActivosFijos if otrosActivosFijos != '' else 0
        balance.equipoTransporte = equipoTransporte if equipoTransporte != '' else 0

        balance.programasComputacionales = programasComputacionales if programasComputacionales != '' else 0
        balance.otros = otros if otros != '' else 0
        balance.amortizaciones = amortizaciones if amortizaciones != '' else 0

        balance.cuentaPorPagar = cuentaPorPagar if cuentaPorPagar != '' else 0
        balance.provedores = provedores if provedores != '' else 0
        balance.retenciones = retenciones if retenciones != '' else 0
        balance.convenioConInstituciones = convenioConInstituciones if convenioConInstituciones != '' else 0
        balance.otros2 = otros2 if otros2 != '' else 0
        balance.acredoresHipotecarios = acredoresHipotecarios if acredoresHipotecarios != '' else 0
        balance.capitalSocial = capitalSocial if capitalSocial != '' else 0
        balance.utilidadesRetenidas = utilidadesRetenidas if utilidadesRetenidas != '' else 0

        balance.fechaCreacion = fechaCreacion if fechaCreacion != '' else datetime.now()

        balance.creador=request.user
        balance.save()
        return redirect('gestion:index')
    
# obtener el detalle del balance
@login_required
def detalleBalance(request,pk):
    try:
        balance = BalanceGeneral.objects.get(pk=pk)
    except BalanceGeneral.DoesNotExist:
        raise Http404("!el balance no existe")
    contexto={
        'b':balance
    }
    return render(request,'gestion/detalleBalance.html',contexto)


# actualizar balance
@login_required
def actualizarBalance(request,pk):

    if request.method == 'GET':
        try:
            balance = BalanceGeneral.objects.get(pk=pk)
        except BalanceGeneral.DoesNotExist:
            raise Http404("!el balance no existe")
        contexto={
            'b':balance
        }
        return render(request,'gestion/actualizarBalance.html',contexto)

    elif request.method == 'POST':
        disponible= request.POST['disponible']
        valoresNegociables = request.POST['valoresNegociables']
        deudoresPorVenta = request.POST['deudoresPorVenta']
        deudoresVarios = request.POST['deudoresVarios']
        impuestosPorRecuperar = request.POST['impuestosPorRecuperar']


        #pasivo circulante
        cuentaPorPagar = request.POST['cuentaPorPagar']
        provedores = request.POST['provedores']
        retenciones = request.POST['retenciones']
        convenioConInstituciones = request.POST['convenioConInstituciones']
        otros = request.POST['otros']

        #activo fijo
        mueblesUtiles = request.POST['mueblesUtiles']
        maquinariaEquipoOficina = request.POST['maquinariaEquipoOficina']
        otrosActivosFijos = request.POST['otrosActivosFijos']
        equipoTransporte = request.POST['equipoTransporte']

        #pasivo fijo
        acredoresHipotecarios = request.POST['acredoresHipotecarios']

        #otros activos
        programasComputacionales = request.POST['programasComputacionales']
        otros2 = request.POST['otros2']
        amortizaciones = request.POST['amortizaciones']

        #capital contable
        capitalSocial = request.POST['capitalSocial']
        utilidadesRetenidas = request.POST['utilidadesRetenidas']

        fechaCreacion = request.POST['fechaCreacion']

        balance = BalanceGeneral.objects.get(id=request.POST['id'])

        balance.disponible = disponible if disponible != '' else 0
        balance.valoresNegociables = valoresNegociables if valoresNegociables != '' else 0
        balance.deudoresPorVenta = deudoresPorVenta if deudoresPorVenta != '' else 0
        balance.deudoresVarios = deudoresVarios  if deudoresVarios != '' else 0
        balance.impuestosPorRecuperar = impuestosPorRecuperar if impuestosPorRecuperar != '' else 0

        balance.mueblesUtiles = mueblesUtiles if mueblesUtiles != '' else 0
        balance.maquinariaEquipoOficina = maquinariaEquipoOficina if maquinariaEquipoOficina != '' else 0
        balance.otrosActivosFijos = otrosActivosFijos if otrosActivosFijos != '' else 0
        balance.equipoTransporte = equipoTransporte if equipoTransporte != '' else 0

        balance.programasComputacionales = programasComputacionales if programasComputacionales != '' else 0
        balance.otros = otros if otros != '' else 0
        balance.amortizaciones = amortizaciones if amortizaciones != '' else 0

        balance.cuentaPorPagar = cuentaPorPagar if cuentaPorPagar != '' else 0
        balance.provedores = provedores if provedores != '' else 0
        balance.retenciones = retenciones if retenciones != '' else 0
        balance.convenioConInstituciones = convenioConInstituciones if convenioConInstituciones != '' else 0
        balance.otros2 = otros2 if otros2 != '' else 0
        balance.acredoresHipotecarios = acredoresHipotecarios if acredoresHipotecarios != '' else 0
        balance.capitalSocial = capitalSocial if capitalSocial != '' else 0
        balance.utilidadesRetenidas = utilidadesRetenidas if utilidadesRetenidas != '' else 0

        balance.fechaCreacion = fechaCreacion if fechaCreacion != '' else datetime.now()

        balance.creador=request.user
        balance.save()
        return redirect('gestion:index')

# eliminar balance
@login_required
def eliminarBalance(request,pk):

    if request.method == 'GET':
        try:
            balance = BalanceGeneral.objects.get(pk=pk)
        except BalanceGeneral.DoesNotExist:
            raise Http404("!el balance no existe")
        contexto={
            'b':balance
        }
        return render(request,'gestion/eliminarBalance.html',contexto)

    elif request.method == 'POST':
        balance = BalanceGeneral.objects.get(id=request.POST['id'])
        balance.delete()
        #eliminamos el registro
        return redirect('gestion:index')
    


#---------------------------------------------------------------- Estado de resultados --------------------------------------------
# crear balance
@login_required
def crearEstadoResultados(request):
    
    if request.method == 'GET':
        contexto = {
            
        }
        return render(request,'gestion/estadoResultados.html',contexto)

    elif request.method == 'POST':
        ventas= request.POST['ventas']
        devolucionesVentas = request.POST['devolucionesVentas']
        descuentosVentas = request.POST['descuentosVentas']
        bonifRebVentas = request.POST['bonifRebVentas']
        inventarioInicial = request.POST['inventarioInicial']


  
        compras = request.POST['compras']

gestion/templates/gestion/actualizarEmpleado.html
{% extends "base_menu.html" %}

{% block head %} 

{% load static %}
{% endblock %}

{% block content %}

<div id="datosEmpleado" class="row col-md-12 d-flex justify-content-center">
    <div class="row col-md-3 d-flex justify-content-center mt-3 inputRounded dark">

      <div class="col-md-12 d-flex justify-content-end close pl-0 pr-0"><i id="form" class="fas fa-times d-flex justify-content-center align-items-center cursorPointer" title="Cerrar" onclick="window.location='{% url 'gestion:factibilidad' %}'" ></i></div>

      <form action="{% url 'gestion:actualizarEmpleado' e.id %}" method="POST" class="col-md-12">
        {% csrf_token %}
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"><h5 class="pr-0 pl-0 text-center col-md-12 mb-0">rellena la información</h5></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2 esconder"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">tipoEmpleado</h5> <input id="tipoEmpleado" name="tipoEmpleado" type="text" class="col-md-6 inputRounded"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Nombre</h5> <input name="nombre" type="text" class="col-md-6 inputRounded" required value="{{ e.nombre }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Apellido paterno</h5> <input name="ap_paterno" type="text" class="col-md-6 inputRounded" required value="{{ e.ap_paterno }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Apellido materno</h5> <input name="ap_materno" type="text" class="col-md-6 inputRounded" required value="{{ e.ap_materno }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Email</h5> <input name="email" type="email" class="col-md-6 inputRounded" required value="{{ e.email }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Telefono</h5> <input name="telefono" type="number" class="col-md-6 inputRounded" required value="{{ e.telefono }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">horas de trabajo</h5> <input name="horas" type="number" class="col-md-6 inputRounded" required value="{{ e.horas }}"></div>
      <div class="col-md-12 d-flex justify-content-center mt-2 mb-2"> <button type="submit" class="col-md-6 btn inputRounded colorSave">Actualizar</button></div>
    </form>

      </div>
  </div>

<br><br><br><br><br>
{% endblock %}


{% block textopie %}
  © 2021 - FinanzasX
  {% endblock %}

gestion/templates/gestion/detalleEmpleado.html
{% extends "base_menu.html" %}

{% block head %} 

{% load static %}
{% endblock %}

{% block content %}

<div id="datosEmpleado" class="row col-md-12 d-flex justify-content-center">
    <div class="row col-md-3 d-flex justify-content-center mt-3 inputRounded dark">

      <div class="col-md-12 d-flex justify-content-end close pl-0 pr-0"><i id="form" class="fas fa-times d-flex justify-content-center align-items-center cursorPointer" title="Cerrar" onclick="window.location='{% url 'gestion:factibilidad' %}'" ></i></div>

      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"><h5 class="pr-0 pl-0 text-center col-md-12 mb-0">rellena la información</h5></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2 esconder"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">tipoEmpleado</h5> <input id="tipoEmpleado" name="tipoEmpleado" type="text" class="col-md-6 inputRounded"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Nombre</h5> <input name="nombre" type="text" class="col-md-6 inputRounded" required value="{{ e.nombre }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Apellido paterno</h5> <input name="ap_paterno" type="text" class="col-md-6 inputRounded" required value="{{ e.ap_paterno }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Apellido materno</h5> <input name="ap_materno" type="text" class="col-md-6 inputRounded" required value="{{ e.ap_materno }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Email</h5> <input name="email" type="email" class="col-md-6 inputRounded" required value="{{ e.email }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Telefono</h5> <input name="telefono" type="number" class="col-md-6 inputRounded" required value="{{ e.telefono }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">horas de trabajo</h5> <input name="horas" type="number" class="col-md-6 inputRounded" required value="{{ e.horas }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Salario por hora</h5> <input name="horas" type="number" class="col-md-6 inputRounded" required value="{{ e.puesto.salario }}"></div>
      

      </div>
  </div>

<br><br><br><br><br>
{% endblock %}


{% block textopie %}
  © 2021 - FinanzasX
  {% endblock %}

gestion/templates/gestion/eliminarEmpleado.html
{% extends "base_menu.html" %}

{% block head %} 

{% load static %}
{% endblock %}

{% block content %}

<div id="datosEmpleado" class="row col-md-12 d-flex justify-content-center">
    <div class="row col-md-3 d-flex justify-content-center mt-3 inputRounded dark">

      <div class="col-md-12 d-flex justify-content-end close pl-0 pr-0"><i id="form" class="fas fa-times d-flex justify-content-center align-items-center cursorPointer" title="Cerrar" onclick="window.location='{% url 'gestion:factibilidad' %}'" ></i></div>

      <form action="{% url 'gestion:eliminarEmpleado' e.id %}" method="POST" class="col-md-12">
        {% csrf_token %}
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"><h5 class="pr-0 pl-0 text-center col-md-12 mb-0">información</h5></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2 esconder"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">id</h5> <input id="tipoEmpleado" name="id" type="text" class="col-md-6 inputRounded" value="{{ e.id }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Nombre</h5> <input name="nombre" type="text" class="col-md-6 inputRounded" required value="{{ e.nombre }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Apellido paterno</h5> <input name="ap_paterno" type="text" class="col-md-6 inputRounded" required value="{{ e.ap_paterno }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Apellido materno</h5> <input name="ap_materno" type="text" class="col-md-6 inputRounded" required value="{{ e.ap_materno }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Email</h5> <input name="email" type="email" class="col-md-6 inputRounded" required value="{{ e.email }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">Telefono</h5> <input name="telefono" type="number" class="col-md-6 inputRounded" required value="{{ e.telefono }}"></div>
      <div class="row col-md-12 pl-0 pr-0 mt-2 mb-2"> <h5 class="pr-0 pl-0 text-center col-md-6 mb-0">horas de trabajo</h5> <input name="horas" type="number" class="col-md-6 inputRounded" required value="{{ e.horas }}"></div>
      <div class="col-md-12 d-flex justify-content-center mt-2 mb-2"> <button type="submit" class="col-md-6 btn inputRounded colorSave">Eliminar</button></div>
    </form>

      </div>
  </div>

<br><br><br><br><br>
{% endblock %}


{% block textopie %}
  © 2021 - FinanzasX
  {% endblock %}

gestion/templates/gestion/index.html
{% extends "base_menu.html" %}

{% load static %}
{% block head %}
<script src="{% static 'js/control.js' %}"></script>
<script src="{% static 'js/actualizar.js' %}"></script>
{% endblock %} 

  




{% block content %}


{% if user.is_authenticated %}
<div class="col-md-12 d-flex justify-content-center mt-5 mb-5">
  <div class="col-md-10  col-sm-12   pl-0 pr-0 d-flex justify-content-center fw-wrap">


    <!-- Estado de resultados  -->

    <div class="col-md-4 dark rounded ml-1 mr-1 pl-0 pr-0 mt-2 mb-2">
      <div class="col-md-12 mt-1 mb-1"><h1 class="text-center">Estado Resultados</h1></div>

    <div class="col-md-12 d-flex justify-content-center mt-1 mb-1">
      <button id="agregar" class="btn colorSave col-md-12 ml-2 mr-2 pl-0 pr-0 boton" onclick="window.location='{% url 'gestion:crearEstadoResultados' %}'">Crear Nuevo</button>
    </div>

    <div id="tableEstadoResultados" class="col-md-12 mt-1 mb-1  ">
      {% for a in listaEstadoResultados %}
      <div class="col-md-12 mt-2 mb-2 d-flex justify-content-between campo"> 
        <input type="date" value="{{ a.fechaCreacion|date:'Y-m-d' }}">
        <li onclick="window.location='{% url 'gestion:eliminarEstadoResultados' a.id %}'" class="fas fa-trash delete d-flex align-items-center" title="Eliminar"></li>
        <li onclick="window.location='{% url 'gestion:actualizarEstadoResultados' a.id %}'" class="fas fa-user-edit d-flex align-items-center update" title="Actualizar"></li>
        <li onclick="window.location='{% url 'gestion:detalleEstadoResultados' a.id %}'" class="fas fa-eye d-flex align-items-center watch" title="Ver"></li>
      </div>
      {% endfor %}      
    </div>
    </div>
  

    <!-- Balance general -->
    <div class="col-md-4   dark rounded ml-1 mr-1 pl-0 pr-0 mt-2 mb-2">
      <div class="col-md-12 mt-1 mb-1"><h1 class="text-center">Balance</h1></div>
    <div class="col-md-12 d-flex justify-content-center mt-1 mb-1">
      <button id="agregar" class="btn colorSave col-md-12 ml-2 mr-2 pl-0 pr-0 boton" onclick="window.location='{% url 'gestion:crearBalance' %}'">Crear Nuevo</button>
    </div>
    <div id="tableEstadoResultados" class="col-md-12 mt-1 mb-1 ">
  
      {% for a in listaBalance %}
      <div class="col-md-12 mt-2 mb-2 d-flex justify-content-between campo"> 
        <input type="date" value="{{ a.fechaCreacion|date:'Y-m-d' }}">
        <li onclick="window.location='{% url 'gestion:eliminarBalance' a.id %}'" class="fas fa-trash delete d-flex align-items-center" title="Eliminar"></li>
        <li onclick="window.location='{% url 'gestion:actualizarBalance' a.id %}'" class="fas fa-user-edit d-flex align-items-center update" title="Actualizar"></li>
        <li onclick="window.location='{% url 'gestion:detalleBalance' a.id %}'" class="fas fa-eye d-flex align-items-center watch" title="Ver"></li>
      </div>
      {% endfor %} 
  
    </div>
    </div>
    
  </div>
</div>
{% else %}
      

{% endif %}





{% endblock %}