Finanzas/urls.py
from django.contrib import admin
from django.urls import path, include
from gestion import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestion/',include('gestion.urls')),
    path('accounts/', include('django.contrib.auth.urls') ),
    path('',views.index)
]

gestion/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name='gestion'
urlpatterns=[
    path('',views.index,name='index'),
    path('crear/empleado',views.index,name='index2'),

    path('crear/balance',views.crearBalance,name='crearBalance'),
    path('detalle/balance/<int:pk>',views.detalleBalance,name='detalleBalance'),
    path('actualizar/balance/<int:pk>',views.actualizarBalance,name='actualizarBalance'),
    path('eliminar/balance/<int:pk>',views.eliminarBalance,name='eliminarBalance'),
    
    path('crear/estadoresultados',views.crearEstadoResultados,name='crearEstadoResultados'),
    path('detalle/estadoresultados/<int:pk>',views.detalleEstadoResultados,name='detalleEstadoResultados'),
    path('actualizar/estadoresultados/<int:pk>',views.actualizarEstadoResultados,name='actualizarEstadoResultados'),
    path('eliminar/estadoresultados/<int:pk>',views.eliminarEstadoResultados,name='eliminarEstadoResultados'),

    path('factibilidad/',views.factibilidad,name="factibilidad"),
    path('detalle/empleado/<int:pk>',views.detalleEmpleado,name="detalleEmpleado"),
    path('actualizar/empleado/<int:pk>',views.actualizarEmpleado,name="actualizarEmpleado"),
    path('eliminar/empleado/<int:pk>',views.eliminarEmpleado,name="eliminarEmpleado")
]

templates/base_bootstrap.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %} " rel="stylesheet">
    <link href="{% static 'css/all.min.css' %} " rel="stylesheet">
    <link href="{% static 'css/main.css' %} " rel="stylesheet">

    <title>{% block title%} {% endblock %}</title>
    {% block head %} {% endblock %}
</head>
<body id="bodu">
    {% block navbar %}{% endblock %}

    {% block content %} {% endblock %}




    <footer class="mifooter dark" >
        <div class="container-fluid">
          <div class="row text-center">
            <div class="col">
              <p class="mb-2 mt-2">{% block textopie %}{% endblock %}</p>
            </div>
          </div>
        </div>
      </footer>
</body>
</html>

templates/base_menu.html
{% extends "base_bootstrap.html" %}

{% load static %}

{% block navbar %}
<nav class="navbar navbar-expand-md navbar-dark black fixed-top" >
    
    <a class="navbar-brand" href="{% url 'gestion:index' %}"><img class="iconLabsol" src="{% static 'images/iconLabsol.png' %}" alt="">FinanzasX</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#barranavegacion" aria-expanded="false" aria-controls="barranavegacion" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="barranavegacion">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'gestion:index' %}">inicio</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'gestion:factibilidad' %}">Factibilidad</a>
          </li>
          {% if user.is_authenticated %}
      <li class="color-blue">
        <i class="fas fa-user icon-user ml-1 mr-1"></i><a class="navbar-brand" href="{% url 'logout' %}?next={% url 'gestion:index' %}">{{ user.get_username }} - Logout</a>
      </li>
      
      {% else %}
      <li class="color-blue">
          <a class="nav-link" href="{% url 'login' %}?next={{request.path}}">Login</a>
      </li>
      {% endif %}            
      </ul>
    </div>
</nav>
{% endblock %}




{% block textopie %}Derechos Reservados FinanzasX{% endblock %}